// Biblioteca de retos. {0}, {1}, {2} = jugadores distintos al azar. {ALL} = todos.
// TAG = etiqueta que se muestra arriba de la carta.
// Modelo "pre-generado": cero coste de IA en cada partida. La IA se usa para AMPLIAR esta lista.

const CHALLENGES = {
  suave: [
    { tag: "Bebe si", text: "Bebe si hoy te has mirado al espejo más de tres veces." },
    { tag: "Bebe si", text: "Bebe si eres el último que ha llegado a la previa." },
    { tag: "Pregunta", text: "<strong>{0}</strong>, cuenta tu plan ideal de finde. Si suena aburrido, bebes." },
    { tag: "Reto", text: "<strong>{0}</strong> imita a <strong>{1}</strong> hasta que el grupo adivine quién es." },
    { tag: "Vota", text: "A la de tres, todos señalan a quién llegaría tarde a su propia boda. El más votado bebe." },
    { tag: "Yo nunca", text: "Yo nunca he mandado un mensaje y me he arrepentido al segundo. Bebe quien sí." },
    { tag: "Reto", text: "<strong>{0}</strong>, haz un brindis épico de 10 segundos. Si no llega, bebes." },
    { tag: "Bebe si", text: "Bebe si tienes más de 1.000 fotos en el móvil." },
    { tag: "Vota", text: "Votad quién es el más dramático del grupo. El elegido bebe." },
    { tag: "Pregunta", text: "<strong>{0}</strong>, ¿cuál fue tu última búsqueda en Google? Léela en alto o bebe doble." },
    { tag: "Reto", text: "<strong>{0}</strong> y <strong>{1}</strong>: pulso de miradas. El primero que se ría, bebe." },
    { tag: "Yo nunca", text: "Yo nunca me he quedado dormido en clase o en el trabajo. Bebe quien sí." },
    { tag: "Bebe si", text: "Bebe si llevas el mismo peinado desde hace más de 3 años." },
    { tag: "Vota", text: "¿Quién es más probable que se haga famoso? Votad. El ganador reparte 2 tragos." },
    { tag: "Reto", text: "<strong>{0}</strong>, di tres cosas buenas de <strong>{1}</strong>. Si dudas, bebes." },
    { tag: "Pregunta", text: "<strong>{0}</strong>, ¿cuál es tu placer culpable musical? Confiésalo o bebe." },
    { tag: "Bebe si", text: "Bebe si has hablado solo hoy." },
    { tag: "Yo nunca", text: "Yo nunca he stalkeado a un ex esta semana. Bebe quien sí." },
    { tag: "Reto", text: "Todos a la vez: vuestra mejor cara de foto de perfil. <strong>{0}</strong> elige la peor y esa persona bebe." },
    { tag: "Vota", text: "Votad al que peor se le da guardar un secreto. Bebe." },
  ],

  picante: [
    { tag: "Yo nunca", text: "Yo nunca me he liado con alguien y al día siguiente no me acordaba de su nombre. Bebe quien sí." },
    { tag: "Reto", text: "<strong>{0}</strong>, enséñale tu última conversación de WhatsApp a <strong>{1}</strong> o bebe 3 tragos." },
    { tag: "Vota", text: "¿Quién tiene más probabilidades de liarse esta noche? El más votado bebe... y avisa." },
    { tag: "Pregunta", text: "<strong>{0}</strong>, ¿con quién de los presentes irías a una isla desierta? Di por qué o bebe." },
    { tag: "Bebe si", text: "Bebe si te has liado con alguien de este grupo o conocido en común." },
    { tag: "Reto", text: "<strong>{0}</strong> hace un cumplido picante a <strong>{1}</strong> sin reírse. Si se ríe, bebe doble." },
    { tag: "Yo nunca", text: "Yo nunca he mentido sobre dónde estaba para librarme de un plan. Bebe quien sí." },
    { tag: "Vota", text: "Votad al más ligón del grupo. Reparte 3 tragos como buen profesional." },
    { tag: "Pregunta", text: "<strong>{0}</strong>, último número que borraste del móvil: ¿por qué? Cuenta o bebe." },
    { tag: "Reto", text: "<strong>{0}</strong> y <strong>{1}</strong>: intercambiad un secreto al oído. El resto bebe de envidia." },
    { tag: "Bebe si", text: "Bebe si alguna vez has fingido que te gustaba un regalo." },
    { tag: "Yo nunca", text: "Yo nunca le he escrito a un ex de madrugada. Bebe quien sí (lo sabemos)." },
    { tag: "Vota", text: "¿Quién es el más intenso en las relaciones? El elegido bebe y se defiende." },
    { tag: "Reto", text: "<strong>{0}</strong>, deja que <strong>{1}</strong> mande un mensaje desde tu móvil a quien quiera... o bebe 4 tragos." },
    { tag: "Pregunta", text: "<strong>{0}</strong>, ¿cuál ha sido tu mayor vergüenza de borrachera? Suéltala o bebe doble." },
    { tag: "Bebe si", text: "Bebe si te has arrepentido de un tatuaje, un piercing o un corte de pelo." },
    { tag: "Vota", text: "Votad quién acabará pidiendo comida a las 4 de la mañana. Bebe el ganador." },
    { tag: "Reto", text: "<strong>{0}</strong>, llama o manda un audio a la última persona con la que hablaste diciendo que la echas de menos." },
    { tag: "Yo nunca", text: "Yo nunca me he hecho el dormido para no hablar con alguien. Bebe quien sí." },
    { tag: "Pregunta", text: "<strong>{0}</strong>, del 1 al 10, ¿cómo de bien besas? Justifícalo o bebe." },
    { tag: "Reto", text: "Todos cierran los ojos. <strong>{0}</strong> señala a quien besaría. Abrid los ojos. Esa persona y {0} brindan." },
    { tag: "Bebe si", text: "Bebe si has tenido un crush con alguien claramente prohibido." },
  ],

  salvaje: [
    { tag: "Reto", text: "<strong>{0}</strong>, deja que el grupo lea tu último mensaje en voz alta. Negarte cuesta 5 tragos." },
    { tag: "Yo nunca", text: "Yo nunca me he liado con dos personas en la misma noche. Bebe quien sí (y cuenta el cómo)." },
    { tag: "Vota", text: "Votad quién tiene el historial de búsqueda más turbio. El elegido lo abre o bebe 4 tragos." },
    { tag: "Reto", text: "<strong>{0}</strong>, intercámbiate una prenda con <strong>{1}</strong> durante las próximas 3 rondas." },
    { tag: "Pregunta", text: "<strong>{0}</strong>, confiesa algo que nadie de este grupo sepa de ti. Si no, bebes 4." },
    { tag: "Reto", text: "<strong>{0}</strong> y <strong>{1}</strong>: 7 minutos sin soltarse de la mano pase lo que pase. Quien suelte, bebe." },
    { tag: "Yo nunca", text: "Yo nunca he tenido un rollo de una noche. Bebe quien sí." },
    { tag: "Vota", text: "¿Quién de aquí ha hecho la mayor locura por amor? Votad, y que lo cuente o beba doble." },
    { tag: "Reto", text: "<strong>{0}</strong>, deja tu móvil desbloqueado en la mesa una ronda entera. O bebe 5 tragos." },
    { tag: "Pregunta", text: "<strong>{0}</strong>, ¿a quién de los presentes te habrías liado en otra vida? Sé sincero o bebe doble." },
    { tag: "Reto", text: "<strong>{0}</strong> manda un audio a su crush diciendo lo que siente. El grupo lo graba. O 6 tragos." },
    { tag: "Yo nunca", text: "Yo nunca me he liado con un ex de un amigo. Bebe quien sí (mira al suelo si hace falta)." },
    { tag: "Vota", text: "Votad a la pareja del grupo que más química tiene. Esos dos hacen un brindis mirándose a los ojos." },
    { tag: "Reto", text: "<strong>{0}</strong>, deja que <strong>{1}</strong> publique una story en tu Instagram. Sin mirar. O bebe 5." },
    { tag: "Pregunta", text: "<strong>{0}</strong>, número de personas con las que te has liado: dilo en alto o bebe un trago por cada una que ocultes." },
    { tag: "Reto", text: "<strong>{0}</strong> hace una declaración de amor falsa pero convincente a <strong>{1}</strong>. Si alguien se ríe, beben los dos." },
    { tag: "Yo nunca", text: "Yo nunca he engañado a alguien. Bebe quien sí... y el grupo decide si seguir hablándote." },
    { tag: "Vota", text: "Votad quién va a ser el primero en vomitar esta noche. El elegido bebe (irónico, lo sabemos)." },
    { tag: "Reto", text: "<strong>{0}</strong>, llama a un ex y dile 'solo quería oír tu voz'. Cuelga rápido. O 6 tragos." },
    { tag: "Pregunta", text: "<strong>{0}</strong>, ¿cuál es tu fantasía más random? Compártela o bebe triple." },
    { tag: "Reto", text: "Los dos que el grupo elija (<strong>{0}</strong> y <strong>{1}</strong>) se sientan en las rodillas del otro una ronda." },
    { tag: "Bebe si", text: "Bebe si te has liado con alguien y nunca se lo has contado a nadie. Ahora puedes... o bebes otra vez." },
  ],

  // 💋 BESTIA — solo grupos mixtos · +18. Todo reto lleva salida ("o bebes"): nadie hace nada que no quiera.
  bestia: [
    { tag: "Atrévete", text: "<strong>{0}</strong> y <strong>{1}</strong>: un beso de 3 segundos. Si alguno no quiere, ese bebe 5 tragos." },
    { tag: "Verdad", text: "<strong>{0}</strong>, ¿a quién de los presentes besarías ahora mismo si no hubiera consecuencias? Dilo o bebe doble." },
    { tag: "Atrévete", text: "<strong>{0}</strong> susurra al oído de <strong>{1}</strong> lo primero que le gustaría hacerle. El resto bebe sin enterarse." },
    { tag: "Reto", text: "<strong>{0}</strong> se sienta en las rodillas de <strong>{1}</strong> durante las próximas 2 rondas. O bebe 4." },
    { tag: "Verdad", text: "<strong>{0}</strong>, puntúa del 1 al 10 el atractivo de <strong>{1}</strong> a la cara. Sé sincero o bebe triple." },
    { tag: "Atrévete", text: "<strong>{0}</strong> elige a alguien del grupo y le da un masaje de hombros de 30 segundos. O ambos beben." },
    { tag: "Verdad", text: "<strong>{0}</strong>, ¿con quién de los presentes has tenido un sueño subidito? Confiesa o bebe doble." },
    { tag: "Atrévete", text: "<strong>{0}</strong> y <strong>{1}</strong>: mirada fija a los ojos 30 segundos sin reírse. Quien se ría o aparte la mirada, bebe." },
    { tag: "Reto", text: "<strong>{0}</strong>, deja que <strong>{1}</strong> te quite una prenda (la que decida {1}, sin pasarse). O bebe 5." },
    { tag: "Verdad", text: "<strong>{0}</strong>, describe tu beso ideal mientras miras a <strong>{1}</strong>. Si te cortas, bebes." },
    { tag: "Atrévete", text: "Botella imaginaria: <strong>{0}</strong> señala a quien quiera besar. Si esa persona acepta, beso. Si no, los dos beben." },
    { tag: "Verdad", text: "<strong>{0}</strong>, ¿qué prefieres de <strong>{1}</strong>: ojos, sonrisa o cuerpo? Responde o bebe doble." },
    { tag: "Reto", text: "<strong>{0}</strong> y <strong>{1}</strong> bailan pegados una canción entera. O cada uno bebe 3 tragos." },
    { tag: "Atrévete", text: "<strong>{0}</strong> le da un beso en la mejilla a la persona que más le atraiga del grupo. O bebe 4." },
    { tag: "Verdad", text: "<strong>{0}</strong>, número de personas con las que te liarías de los presentes. Di cuántos (sin nombres) o bebe por cada uno." },
    { tag: "Atrévete", text: "<strong>{0}</strong> elige: beso a <strong>{1}</strong> o confiesa tu mayor fantasía al grupo. Lo que no elijas, 4 tragos." },
    { tag: "Reto", text: "<strong>{0}</strong> escribe por privado a <strong>{1}</strong> algo atrevido AHORA. {1} decide si lo lee en alto. O {0} bebe 5." },
    { tag: "Verdad", text: "<strong>{0}</strong>, ¿alguna vez has pensado en alguien de este grupo de forma nada inocente? Sincérate o bebe triple." },
    { tag: "Atrévete", text: "Minuto del cielo: <strong>{0}</strong> y <strong>{1}</strong> desaparecen 1 minuto. Lo que pase, pasa. O cada uno bebe 5." },
    { tag: "Verdad", text: "<strong>{0}</strong>, si tuvieras que liarte con alguien de aquí esta noche, ¿quién sería tu top 2? Di o bebe doble por cada uno." },
    { tag: "Reto", text: "<strong>{0}</strong> le hace un baile sexy de 15 segundos a <strong>{1}</strong>. Sin reírse. O bebe 4." },
  ],
};

// ---------- LA MONEDA: preguntas "¿Quién es más...?" por estilo ----------
// {0} = quien decide. Señala en secreto; la moneda decide si se revela.
// NORMAL: vale para cualquier grupo (solo chicos, solo chicas o mixto).
// MIXTO: para grupos con chicos y chicas (atracción entre los presentes).
const COIN_QUESTIONS = {
  normal: [
    "haya sido infiel alguna vez",
    "haya fingido un orgasmo",
    "se haya liado con alguien estando con otra persona",
    "tenga fotos comprometidas en el móvil ahora mismo",
    "haya mentido sobre con cuánta gente se ha liado",
    "haya stalkeado a su ex hoy",
    "siga colgado de un ex sin admitirlo",
    "tenga un lío que nadie de aquí sabe",
    "se arrepienta de algo que hizo borracho",
    "haya mandado un nude alguna vez",
    "haya pensado en dejar a su pareja",
    "haya ligado por encima de sus posibilidades",
    "tenga el historial de búsqueda más turbio",
    "haya hecho (o querría hacer) un trío",
    "sea el peor en la cama, según el grupo",
    "haya mentido a su pareja esta semana",
    "haya tenido sexting con un desconocido",
    "sea el más salido del grupo",
    "se haya liado con alguien y lo niegue",
    "haya llorado por un rollo de una noche",
    "tenga el peor historial de relaciones",
    "haya espiado el móvil de su pareja",
  ],
  mixto: [
    "se liaría con alguien de esta sala",
    "esté pensando en alguien de aquí ahora mismo",
    "se haya fijado en alguien del grupo y lo disimule",
    "sea el mejor besando de los presentes",
    "se liaría contigo si te lanzaras",
    "haya tenido un sueño subido de tono con alguien de aquí",
    "acabe liándose esta noche con alguien del grupo",
    "le pondría los cuernos a su pareja con alguien de aquí",
    "te atraiga más de lo que admites",
    "sería tu mejor rollo de una noche de los presentes",
    "se atrevería con dos de los presentes a la vez",
    "tenga tensión con alguien de la sala",
  ],
};
